management:
  endpoint:
    health:
      show-details: ALWAYS
  health:
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j.ratelimiter:
  instances:
    simpleRateLimit:
      limitForPeriod: 2
      # limitRefreshPeriod: 15s
      limitRefreshPeriod: 2s
      timeoutDuration: 1s
      registerHealthIndicator: true
      subscribeForEvents: true
    rateLimiterEventsExample:
      limitForPeriod: 2
      limitRefreshPeriod: 10s
      timeoutDuration: 5s
      registerHealthIndicator: true
      subscribeForEvents: true

cron_params:
  sync:
    cron:
      every_second: '* * * * * *'
      every_minute: '0 * * * * *'
      every_hour: '0 0 * * * *'
      1_sec_before_midnight: '0 26 17 * * *'

notifications:
  cron: '* * * * * *'

notification:
  email:
    from: 'Sende1r'
    to: Receiver_1, Receiver_2, Receiver_3
    to_list: [ "health", "metrics", "prometheus" ]

spring:
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'XXXXXXXXXXX'
    password: 'xxxxxxx'

    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
