
services:

    mysql_database:
        hostname: mysql_database
        restart: always
        container_name: mysql_database

        image: mysql
        # image: mysql:latest

        volumes:
            - /tmp/docker/test_database/mysql:/var/lib/mysql

        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_database
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=qwerty12345

        ports:
            - 3306:3306/tcp
            - 33060:33060/tcp

        network_mode: "host"   


networks:
    host:
        name: host
        external: true