

#  Exclude DataSourceAutoConfiguration : https://www.baeldung.com/spring-boot-failed-to-configure-data-source
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: HEADERS

service:
  api:
    url: 'http://0.0.0.0:52525'


