

#  Exclude DataSourceAutoConfiguration : https://www.baeldung.com/spring-boot-failed-to-configure-data-source
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

service:
  api:
    url: 'http://localhost:50002'